// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuOPRUEe11VZsbJDKbvfiMS9E6u-x74U',
    appId: '1:16618628362:web:646ee65ac3cfd51cacc6f3',
    messagingSenderId: '16618628362',
    projectId: 'appnotes-4be34',
    authDomain: 'appnotes-4be34.firebaseapp.com',
    databaseURL: 'https://appnotes-4be34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appnotes-4be34.firebasestorage.app',
    measurementId: 'G-B6VM40V9WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrt7OkInJiVpUqKNggpG22FkD4CsRg0WA',
    appId: '1:16618628362:android:e11d2ba09588757aacc6f3',
    messagingSenderId: '16618628362',
    projectId: 'appnotes-4be34',
    databaseURL: 'https://appnotes-4be34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appnotes-4be34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQaPzhzbRw9sf6WCwBsbPhUV7mTcpmLg',
    appId: '1:16618628362:ios:ff63047e64722dd3acc6f3',
    messagingSenderId: '16618628362',
    projectId: 'appnotes-4be34',
    databaseURL: 'https://appnotes-4be34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appnotes-4be34.firebasestorage.app',
    androidClientId: '16618628362-mnb4d5lb66u1u3b6dc8qf289iltcge83.apps.googleusercontent.com',
    iosClientId: '16618628362-ieehfvsnd81ai7jdd8el4v9lckpold1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQaPzhzbRw9sf6WCwBsbPhUV7mTcpmLg',
    appId: '1:16618628362:ios:ff63047e64722dd3acc6f3',
    messagingSenderId: '16618628362',
    projectId: 'appnotes-4be34',
    databaseURL: 'https://appnotes-4be34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appnotes-4be34.firebasestorage.app',
    androidClientId: '16618628362-mnb4d5lb66u1u3b6dc8qf289iltcge83.apps.googleusercontent.com',
    iosClientId: '16618628362-ieehfvsnd81ai7jdd8el4v9lckpold1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcuOPRUEe11VZsbJDKbvfiMS9E6u-x74U',
    appId: '1:16618628362:web:7fc2d0465c4c994facc6f3',
    messagingSenderId: '16618628362',
    projectId: 'appnotes-4be34',
    authDomain: 'appnotes-4be34.firebaseapp.com',
    databaseURL: 'https://appnotes-4be34-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appnotes-4be34.firebasestorage.app',
    measurementId: 'G-5KHLJ7HMCW',
  );

}